# This workflow will build and push a .NET Core application to an Azure Web App on every push to the main branch.
#
# To configure this workflow:
# 1. Set up secrets
#     AZURE_CUSTOMER_WEBAPP_NAME - set to the name of the publisher APP
#     AZURE_CUSTOMER_WEBAPP_PUBLISH_PROFILE - upload contents of Azure Customer App publish profile.
#     AZURE_PUBLISHER_WEBAPP_NAME - set to the name of the publisher APP
#     AZURE_PUBLISHER_WEBAPP_PUBLISH_PROFILE - upload contents of Azure Publisher App publish profile.

name: "Deploy WEB Apps to dev"

on:
  push:
    branches:
      - main

env:  
  CUSTOMER_PROJECT: './src/SaaS.SDK.CustomerProvisioning/SaaS.SDK.CustomerProvisioning.csproj'
  CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH: './src/SaaS.SDK.CustomerProvisioning/publish'
  PUBLISHER_PROJECT: './src/SaaS.SDK.PublisherSolution/SaaS.SDK.PublisherSolution.csproj'
  PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH: './src/SaaS.SDK.PublisherSolution/publish'
  DOTNET_CORE_VERSION: '6.0.3'
  
jobs:
  deploytocustomer:
    name: Deploy customer app to dev
    runs-on: ubuntu-latest
    environment: dev

    steps:

    # Checkout the repo
    - uses: actions/checkout@main

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }} 

    # Run dotnet build and publish
    - name: Build app
      run: |
        dotnet build ${{ env.CUSTOMER_PROJECT }} --configuration Release
        dotnet publish ${{ env.CUSTOMER_PROJECT }} --configuration Release --no-build --output ${{ env.CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH }}

    # Deploy to Azure Web app
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_CUSTOMER_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_CUSTOMER_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH }}

  deploytopublisher:
    name: Deploy publisher app to dev
    runs-on: ubuntu-latest
    environment: dev

    steps:

    # Checkout the repo
    - uses: actions/checkout@main

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }} 

    # Run dotnet build and publish
    - name: Build app
      run: |
        dotnet build ${{ env.PUBLISHER_PROJECT }} --configuration Release
        dotnet publish ${{ env.PUBLISHER_PROJECT }} --configuration Release --no-build --output ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}

    # Deploy to Azure Web app
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_PUBLISHER_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISHER_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}
    
